api_version = "unstable"

[[extensions]]
type = "ui_extension"
name = "My wishlist"
handle = "wishlist-extension-react"

[[extensions.targeting]]
module = "./src/FullPageExtension.tsx"
target = "customer-account.page.render"

[extensions.capabilities]
api_access = true
